Game logic
adaorachi/tic_tac_toe pull request #1
Opened 2019-11-04 16:09 UTC by kazumaki

We had to create another repository to fix stickler, it was not working on our last one.

2019-11-05 16:45 UTC, maelfosso requested changes
# Changes required

Hello coders,

Really nice code, nice game boards, nice nice nice :clap: 
However just a few things to changes.

- Make **bin/main.rb** executable such that we could run the game by only entering `bin/main.rb`

- There is no message when the game is a **Tie / Draw**
```ruby
Available      TIC-TAC_TOE
moves

  |   |         X | X | O
---------       --------- 
  |   |         O | O | X
---------       --------- 
  |   |         X | O | X


Do you want to play again (y/n)
```
- Read the comment below to fix some changes

Kindly make the changes and submit a new code review request.
Thanks

**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com) | [LinkedIn](https://www.linkedin.com/in/mael-elvis-fosso-650b6346/)

2019-11-05 16:45 UTC, maelfosso commented on bin/main.rb
> +  current_player = current_player.name == game.board.player1.name ? game.board.player2 : game.board.player1
You could put it into the `Game` class
1. Create a property  (reader) **current_player**
2. Create a method **switch_player** for example
3. And
```ruby
def switch_player
    @current_player = @current_player.name == player1.name ? player2 : player1
end
```

2019-11-05 16:45 UTC, maelfosso commented on bin/main.rb
> +game.start_board(player_first, player_second, marker1, marker2)
Constructor of **Game** class

2019-11-05 16:45 UTC, maelfosso commented on bin/main.rb
> +current_player = player_first == game.board.player1.name ? game.board.player1 : game.board.player2
move it into the constructor of **Game** class

2019-11-05 16:45 UTC, maelfosso commented on lib/board.rb
> +    @player2 = Player.new(player2, marker2)
Move it into the **Game** class
The Players are part of the Game not of the Board

2019-11-06 18:48 UTC, whiz25 approved these changes
## Cool! :clap: 
I tested your app, it works properly. All requirements met so it's a :+1:  from me.

### Martin Afani

2019-11-06 22:34 UTC, merged